// SPDX-License-Identifier: GPL-2.0
/*
        Kernel functions, rewritten in assembly.

        LICENSE. This file is a derivative work of the Linux kernel and is
        licensed under the GNU General Public License, version 2 only
        (SPDX: GPL-2.0), the same terms as Linux itself. Every routine below
        is a port of a function of the kernel, named in the index and at the
        routine; the algorithm, the data structures and the behaviour, error
        paths included, are the original's, and the copyright in each belongs
        to the authors named in the header of the kernel file it comes from
        (fs/ext4/namei.c: Remy Card, Linus Torvalds, David S. Miller,
        Theodore Ts'o, Daniel Phillips, Christopher Li). Nothing in this
        file is offered under any other license.

        That is a fact about this one file. The rest of this repository is
        under the license in .github/LICENSE; the routines in src/lib.c that these
        call -- the sixteen name half_md4 hash is the first -- keep theirs,
        and are linked into the same kernel image, which as a whole is a
        GPL-2.0 work as any kernel with a built-in module is. A change to a routine
        here is a change to a GPL-2.0 file and is contributed as one.

        WHAT IT IS. lib.c's style, for the kernel's own functions: top-level
        asm, one ASM_FUNC to a routine, no C body anywhere in it. Where a C
        function of the kernel is hot enough to be worth it, it is written
        here from the top instead of patched, and kernel/patch/functions
        retires the C original, so the asm symbol takes its place and the
        compiler has no say in how that function runs. Only the architectures
        a routine says it covers are replaced; on the others the C stays.

        HOW IT IS PICKED. Comments of the form //> directly above a routine
        say what it replaces and what it needs, and kernel/patch/functions
        reads them (see that file for the grammar): which kernel function
        stops being C, which functions and structure offsets the asm needs
        from the kernel, and which values it takes as literals and the build
        checks. The kernel's structure offsets are the compiler's own for the
        configuration being built -- generated into asm-offsets.h through the
        architecture's asm-offsets.c -- and this file names them through
        MWSET, never as numbers. MOONWATER_STOCK builds none of it.

        The index. Generated by kernel/patch/functions --index -- do not edit
        by hand; edit the tags and run it again.

//  (index begin)
//    routine                 replaces                                x86_64  arm64   riscv64 measured
//    ----------------------  --------------------------------------  ------- ------- ------- --------
//    htree_dirblock_to_tree  fs/ext4/namei.c htree_dirblock_to_tree  yes     no      no      getdents: 1000 names 92.5 -> 52.5 us (-43%), 100 names -36%, 16 names -19%; 8 names level
//
//    1 routine.
//  (index end)
*/

#ifndef KERNEL_KERNEL_C
#define KERNEL_KERNEL_C

// A kernel offset or constant as an assembler symbol: .set NAME, <its value>.
// The value is the compiler's, from include/generated/asm-offsets.h, and the
// assembler then knows it as a plain absolute symbol, so a displacement is
// encoded as short as it can be.
#define MWSET(name) ".set " #name ", " __stringify(name) "\n"

#ifdef CONFIG_X86_64
#include <generated/asm-offsets.h>

// The one declaration in the file that is not assembly: a module parameter,
// moonwater.dirhash_simd=0, which turns the wide directory hash off for a
// machine where it misbehaves and for timing one against the other. The
// routine below reads the variable.
bool moonwater_dirhash_simd = true;
module_param_named(dirhash_simd, moonwater_dirhash_simd, bool, 0644);
#endif

//
//       htree_dirblock_to_tree -- fs/ext4/namei.c
//
//       int htree_dirblock_to_tree(struct file *dir_file, struct inode *dir,
//                                  ext4_lblk_t block, struct dx_hash_info *hinfo,
//                                  __u32 start_hash, __u32 start_minor_hash)
//
//       Reads one directory block and puts its live entries in the red-black
//       tree readdir walks, in hash order. Every getdents on an ext4
//       directory runs this over every block, and it hashes every name in it:
//       a directory of one block is read in hash order like any other and
//       the hash is stored nowhere. In a guest running this kernel, over a
//       directory of a thousand names, ext4fs_dirhash and its packer were 47%
//       of the syscall.
//
//       The walk is the C function's, step for step, with two changes that
//       are the point. The entry check is written out: the seven conditions
//       of __ext4_check_dir_entry for an ordinary entry are tested here, in
//       registers, and the real function is called for anything the fast
//       test is not certain of -- a fake entry ("." and "..", the checksum
//       tail), a directory that keeps hashes in its entries, and any entry
//       that fails -- so an error is reported by the same code, with the same
//       words, as ever. And the hash is not asked for a name at a time: on a
//       directory of half_md4 names that are neither encrypted nor
//       casefolded, the first live entry sends the next up to sixty four
//       names, sixteen to a call, to hash_half_md4_wide (src/lib.c), which
//       runs sixteen names side by side. A hash is a pure function of the
//       name, the seed and the version, so the answer taken from the batch is
//       the answer ext4fs_dirhash gives. Anything the batch does not cover
//       goes to ext4fs_dirhash as before: a name whose 32-byte windows
//       would end outside the block, a block with fewer than sixteen names
//       left, a machine without AVX2, a context that may not use the vector
//       registers, and moonwater.dirhash_simd=0.
//
//       An entry with no inode is skipped by the walk whatever its hash is,
//       so with the batch on it is not hashed at all.
//
//       MEASURED. One getdents64 pass over one directory, microseconds, in a
//       KVM guest on a Ryzen 9 9950X (Zen 5), minimum over hundreds of short
//       bursts, ext4 as the installer makes it. "before" is this kernel with
//       the C function; "port" is this routine; "wide off" is the same image as
//       "port" booted with moonwater.dirhash_simd=0, which is the control:
//
//           directory                before    port   wide off   port vs before
//           1000 names, 35 chars       92.5    52.5      91.1        -43.2%
//           1000 names, 10 chars       65.9    42.4      65.4        -35.7%
//           5000 names                387.3   261.9     374.9        -32.4%
//           100 names                  6.53    4.21      6.33        -35.6%
//           50 names                   3.40    2.30      3.34        -32.2%
//           24 names                   1.80    1.32      1.77        -26.8%
//           20 names                   1.55    1.18      1.54        -23.5%
//           16 names                   1.30    1.05      1.30        -19.0%
//           15 names                   1.23    1.02      1.24        -17.3%
//           8 names                   0.805   0.821     0.813         +1.9%
//
//       The control is the point. With the wide hash off, this routine is
//       level with the C it replaced: written out from the top, the walk and
//       the inlined entry checks come to what GCC made of the C, no better
//       and no worse, so none of the gain is "assembly beats the compiler".
//       All of it is the sixteen-name hash, which the compiler cannot make
//       from a loop over one name at a time. Below sixteen live names in a
//       block the batch is not used and the routine is level with the C.
//       Nothing else in the kernel moved by more than the noise (about 4%):
//       open, stat, read, write, create, unlink and rename are the same.
//       The hash on its own, per name: 19 ticks against 96 on Zen 5 (5.0x),
//       7.6 ns against 22.6 on an Apple M-series (3.0x); riscv64 is untimed.
//       Checked against the kernel's own hash on all three architectures,
//       and the directory stream it produces is byte for byte the stock
//       kernel's: see test/differential.py --harness kernel_dirhash.
//
//       Registers: r12 dir_file, r13 dir, r14 hinfo, r15 bh, rbx the entry,
//       rbp where the entries end. Stack arguments to __ext4_check_dir_entry
//       are the bottom of the frame. DIRENT_HTREE is passed as the literal
//       3; the build asserts it, in namei.c, where the enum is.
//
//> arch x86_64
//> perf getdents: 1000 names 92.5 -> 52.5 us (-43%), 100 names -36%, 16 names -19%; 8 names level
//> replace fs/ext4/namei.c htree_dirblock_to_tree
//> unstatic fs/ext4/namei.c __ext4_read_dirblock
//> assert fs/ext4/namei.c DIRENT_HTREE == 3
//> include <linux/buffer_head.h>
//> include <linux/fs.h>
//> include <asm/cpufeatures.h>
//> include <asm/processor.h>
//> include "../../../fs/ext4/ext4.h"
//> offset MW_INODE_SB inode i_sb
//> offset MW_INODE_FLAGS inode i_flags
//> offset MW_INODE_BLKBITS inode i_blkbits
//> offset MW_SB_BLOCKSIZE super_block s_blocksize
//> offset MW_SB_FS_INFO super_block s_fs_info
//> offset MW_SBI_ES ext4_sb_info s_es
//> offset MW_ES_INODES ext4_super_block s_inodes_count
//> offset MW_ES_RO_COMPAT ext4_super_block s_feature_ro_compat
//> offset MW_BH_DATA buffer_head b_data
//> offset MW_BH_SIZE buffer_head b_size
//> offset MW_DX_HASH dx_hash_info hash
//> offset MW_DX_MINOR dx_hash_info minor_hash
//> offset MW_DX_VERSION dx_hash_info hash_version
//> offset MW_DX_SEED dx_hash_info seed
//> offset MW_CPU_CAP cpuinfo_x86 x86_capability
//> const MW_DX_HALF_MD4 DX_HASH_HALF_MD4
//> const MW_DX_HALF_MD4_U DX_HASH_HALF_MD4_UNSIGNED
//> const MW_S_ENCRYPTED S_ENCRYPTED
//> const MW_S_CASEFOLD S_CASEFOLD
//> const MW_CSUM_FEATURE EXT4_FEATURE_RO_COMPAT_METADATA_CSUM
//> const MW_FT_DIR_CSUM EXT4_FT_DIR_CSUM
//> const MW_NAME_LEN EXT4_NAME_LEN
//> const MW_AVX2_WORD (X86_FEATURE_AVX2 >> 5)
//> const MW_AVX2_BIT (X86_FEATURE_AVX2 & 31)
#ifdef CONFIG_X86_64
__asm__(
    MWSET(MW_INODE_SB)
    MWSET(MW_INODE_FLAGS)
    MWSET(MW_INODE_BLKBITS)
    MWSET(MW_SB_BLOCKSIZE)
    MWSET(MW_SB_FS_INFO)
    MWSET(MW_SBI_ES)
    MWSET(MW_ES_INODES)
    MWSET(MW_ES_RO_COMPAT)
    MWSET(MW_BH_DATA)
    MWSET(MW_BH_SIZE)
    MWSET(MW_DX_HASH)
    MWSET(MW_DX_MINOR)
    MWSET(MW_DX_VERSION)
    MWSET(MW_DX_SEED)
    MWSET(MW_CPU_CAP)
    MWSET(MW_DX_HALF_MD4)
    MWSET(MW_DX_HALF_MD4_U)
    MWSET(MW_S_ENCRYPTED)
    MWSET(MW_S_CASEFOLD)
    MWSET(MW_CSUM_FEATURE)
    MWSET(MW_FT_DIR_CSUM)
    MWSET(MW_NAME_LEN)
    MWSET(MW_AVX2_WORD)
    MWSET(MW_AVX2_BIT)
    ".set L_ARGS, 0\n"
    ".set L_FSTR, 32\n"
    ".set L_TMP, 48\n"
    ".set L_BLOCK, 64\n"
    ".set L_SHASH, 68\n"
    ".set L_SMINOR, 72\n"
    ".set L_COUNT, 76\n"
    ".set L_ON, 80\n"
    ".set L_MCOUNT, 84\n"
    ".set L_MNEXT, 88\n"
    ".set L_FLAGS, 92\n"
    ".set L_STATE, 96\n"
    ".set L_BUF, 112\n"
    ".set L_END, 120\n"
    ".set L_BLKSZ, 128\n"
    ".set L_INODES, 132\n"
    ".set L_HID, 136\n"
    ".set L_SAVELEN, 140\n"
    ".set L_K, 144\n"
    ".set L_NCHUNK, 148\n"
    ".set L_N, 152\n"
    ".set L_AT, 160\n"
    ".set L_NOFF, 288\n"
    ".set L_LEN, 544\n"
    ".set L_RES, 800\n"
    ".set L_FRAME, 1320\n"
);

__asm__(
    ASM_FUNC(htree_dirblock_to_tree)
    "        push    %rbp\n"
    "        push    %r15\n"
    "        push    %r14\n"
    "        push    %r13\n"
    "        push    %r12\n"
    "        push    %rbx\n"
    "        sub     $L_FRAME, %rsp\n"
    "        mov     %rdi, %r12\n"
    "        mov     %rsi, %r13\n"
    "        mov     %rcx, %r14\n"
    "        mov     %edx, L_BLOCK(%rsp)\n"
    "        mov     %r8d, L_SHASH(%rsp)\n"
    "        mov     %r9d, L_SMINOR(%rsp)\n"
    "        movl    $0, L_COUNT(%rsp)\n"
    "        movq    $0, L_FSTR(%rsp)\n"
    "        movq    $0, L_FSTR+8(%rsp)\n"
    "        # bh = ext4_read_dirblock(dir, block, DIRENT_HTREE): __ext4_read_dirblock(dir, block, 3, __func__, line)\n"
    "        mov     %r13, %rdi\n"
    "        mov     L_BLOCK(%rsp), %esi\n"
    "        mov     $3, %edx\n"
    "        lea     .Lmw_fn(%rip), %rcx\n"
    "        mov     $1051, %r8d\n"
    "        call    __ext4_read_dirblock\n"
    "        cmp     $-4095, %rax\n"
    "        jae     .Lmw_readerr\n"
    "        mov     %rax, %r15\n"
    "        # the block: where it starts and ends, how many inodes there are, whether checksums are on\n"
    "        mov     MW_BH_DATA(%r15), %rbx\n"
    "        mov     %rbx, L_BUF(%rsp)\n"
    "        mov     MW_INODE_SB(%r13), %rax\n"
    "        mov     MW_SB_BLOCKSIZE(%rax), %ecx\n"
    "        mov     %ecx, L_BLKSZ(%rsp)\n"
    "        lea     (%rbx,%rcx), %rdx\n"
    "        mov     %rdx, L_END(%rsp)\n"
    "        mov     MW_SB_FS_INFO(%rax), %rdx\n"
    "        mov     MW_SBI_ES(%rdx), %rdx\n"
    "        mov     MW_ES_INODES(%rdx), %esi\n"
    "        mov     %esi, L_INODES(%rsp)\n"
    "        xor     %esi, %esi\n"
    "        testl   $MW_CSUM_FEATURE, MW_ES_RO_COMPAT(%rdx)\n"
    "        setnz   %sil\n"
    "        # ext4_hash_in_dirent(dir): casefolded and encrypted both\n"
    "        mov     MW_INODE_FLAGS(%r13), %eax\n"
    "        and     $(MW_S_ENCRYPTED|MW_S_CASEFOLD), %eax\n"
    "        cmp     $(MW_S_ENCRYPTED|MW_S_CASEFOLD), %eax\n"
    "        sete    %dl\n"
    "        movzbl  %dl, %edx\n"
    "        mov     %edx, L_HID(%rsp)\n"
    "        # top = de + blocksize - ext4_dir_rec_len(0, csum ? NULL : dir): 8, and 8 more where the entries carry hashes\n"
    "        mov     $8, %edi\n"
    "        test    %esi, %esi\n"
    "        jnz     1f\n"
    "        lea     (%rdi,%rdx,8), %edi\n"
    "1:\n"
    "        mov     L_END(%rsp), %rbp\n"
    "        sub     %rdi, %rbp\n"
#ifdef CONFIG_FS_ENCRYPTION
    "        testl   $MW_S_ENCRYPTED, MW_INODE_FLAGS(%r13)\n"
    "        jz      .Lmw_setup\n"
    "        mov     %r13, %rdi\n"
    "        call    __fscrypt_prepare_readdir\n"
    "        test    %eax, %eax\n"
    "        js      .Lmw_brelse_exit\n"
    "        mov     $MW_NAME_LEN, %edi\n"
    "        lea     L_FSTR(%rsp), %rsi\n"
    "        call    fscrypt_fname_alloc_buffer\n"
    "        test    %eax, %eax\n"
    "        js      .Lmw_brelse_exit\n"
#endif
    ".Lmw_setup:\n"
    "        # the batch is for half_md4 names that are neither encrypted nor casefolded\n"
    "        movl    $0, L_ON(%rsp)\n"
    "        movl    $0, L_MCOUNT(%rsp)\n"
    "        movl    $0, L_MNEXT(%rsp)\n"
    "        testl   $(MW_S_ENCRYPTED|MW_S_CASEFOLD), MW_INODE_FLAGS(%r13)\n"
    "        jnz     .Lmw_loop\n"
    "        mov     MW_DX_VERSION(%r14), %eax\n"
    "        xor     %edx, %edx\n"
    "        cmp     $MW_DX_HALF_MD4, %eax\n"
    "        je      1f\n"
    "        cmp     $MW_DX_HALF_MD4_U, %eax\n"
    "        jne     .Lmw_loop\n"
    "        mov     $1, %edx\n"
    "1:\n"
    "        mov     %edx, L_FLAGS(%rsp)\n"
    "        movl    $1, L_ON(%rsp)\n"
    "        movl    $0x67452301, L_STATE(%rsp)\n"
    "        movl    $0xefcdab89, L_STATE+4(%rsp)\n"
    "        movl    $0x98badcfe, L_STATE+8(%rsp)\n"
    "        movl    $0x10325476, L_STATE+12(%rsp)\n"
    "        mov     MW_DX_SEED(%r14), %rax\n"
    "        test    %rax, %rax\n"
    "        jz      .Lmw_loop\n"
    "        mov     (%rax), %ecx\n"
    "        or      4(%rax), %ecx\n"
    "        or      8(%rax), %ecx\n"
    "        or      12(%rax), %ecx\n"
    "        jz      .Lmw_loop\n"
    "        mov     (%rax), %ecx\n"
    "        mov     %ecx, L_STATE(%rsp)\n"
    "        mov     4(%rax), %ecx\n"
    "        mov     %ecx, L_STATE+4(%rsp)\n"
    "        mov     8(%rax), %ecx\n"
    "        mov     %ecx, L_STATE+8(%rsp)\n"
    "        mov     12(%rax), %ecx\n"
    "        mov     %ecx, L_STATE+12(%rsp)\n"

    "        # for (; de < top; de = ext4_next_entry(de, blocksize))\n"
    ".Lmw_loop:\n"
    "        cmp     %rbp, %rbx\n"
    "        jae     .Lmw_done\n"
    "        # ext4_check_dir_entry: the seven tests for an ordinary entry, in registers\n"
    "        movzwl  4(%rbx), %eax\n"
    "        lea     -1(%rax), %ecx\n"
    "        cmp     $0xfffe, %ecx\n"
    "        jae     7f\n"
    "        mov     %eax, %ecx\n"
    "        and     $0xfffc, %eax\n"
    "        and     $3, %ecx\n"
    "        shl     $16, %ecx\n"
    "        or      %ecx, %eax\n"
    "        jmp     8f\n"
    "7:\n"
    "        mov     L_BLKSZ(%rsp), %eax\n"
    "8:\n"
    "        mov     %rbx, %rdx\n"
    "        sub     L_BUF(%rsp), %rdx\n"
    "        lea     (%rdx,%rax), %ecx\n"
    "        movzbl  6(%rbx), %esi\n"
    "        cmpl    $0, L_HID(%rsp)\n"
    "        jne     .Lmw_slow\n"
    "        cmp     $12, %eax\n"
    "        jl      .Lmw_slow\n"
    "        test    $3, %al\n"
    "        jnz     .Lmw_slow\n"
    "        lea     11(%rsi), %edi\n"
    "        and     $-4, %edi\n"
    "        cmp     %edi, %eax\n"
    "        jl      .Lmw_slow\n"
    "        mov     MW_BH_SIZE(%r15), %r8d\n"
    "        cmp     %r8d, %ecx\n"
    "        jg      .Lmw_slow\n"
    "        lea     -12(%r8), %edi\n"
    "        cmp     %edi, %ecx\n"
    "        jle     1f\n"
    "        cmp     %r8d, %ecx\n"
    "        jne     .Lmw_slow\n"
    "1:\n"
    "        mov     (%rbx), %edi\n"
    "        cmp     L_INODES(%rsp), %edi\n"
    "        ja      .Lmw_slow\n"
    "        cmp     %r8d, %ecx\n"
    "        jne     2f\n"
    "        cmp     $1, %esi\n"
    "        jne     2f\n"
    "        cmpb    $'.', 8(%rbx)\n"
    "        je      .Lmw_slow\n"
    "2:\n"
    "        cmpb    $MW_FT_DIR_CSUM, 7(%rbx)\n"
    "        je      .Lmw_slow\n"
    "        lea     -1(%rsi), %edi\n"
    "        cmp     $1, %edi\n"
    "        ja      .Lmw_ok\n"
    "        cmpb    $'.', 8(%rbx)\n"
    "        jne     .Lmw_ok\n"
    "        cmpb    $'.', 9(%rbx)\n"
    "        je      .Lmw_slow\n"
    "        cmpb    $0, 9(%rbx)\n"
    "        je      .Lmw_slow\n"
    "        jmp     .Lmw_ok\n"

    "        # not certain: the real __ext4_check_dir_entry, which also says what is wrong\n"
    ".Lmw_slow:\n"
    "        mov     L_BLOCK(%rsp), %eax\n"
    "        movzbl  MW_INODE_BLKBITS(%r13), %ecx\n"
    "        shl     %cl, %rax\n"
    "        mov     %rbx, %rdx\n"
    "        sub     L_BUF(%rsp), %rdx\n"
    "        add     %rdx, %rax\n"
    "        mov     %eax, %eax\n"
    "        mov     %rax, 16(%rsp)\n"
    "        mov     L_BUF(%rsp), %rax\n"
    "        mov     %rax, 0(%rsp)\n"
    "        mov     MW_BH_SIZE(%r15), %eax\n"
    "        mov     %rax, 8(%rsp)\n"
    "        lea     .Lmw_fn(%rip), %rdi\n"
    "        mov     $1077, %esi\n"
    "        mov     %r13, %rdx\n"
    "        xor     %ecx, %ecx\n"
    "        mov     %rbx, %r8\n"
    "        mov     %r15, %r9\n"
    "        call    __ext4_check_dir_entry\n"
    "        test    %eax, %eax\n"
    "        jnz     .Lmw_done\n"

    "        # the hash: from the batch, from the entry itself, or from ext4fs_dirhash\n"
    ".Lmw_ok:\n"
    "        cmpl    $0, L_HID(%rsp)\n"
    "        jne     .Lmw_hid\n"
    "        cmpl    $0, L_ON(%rsp)\n"
    "        je      .Lmw_scalar\n"
    "        cmpl    $0, (%rbx)\n"
    "        je      .Lmw_next\n"
    "        mov     L_MNEXT(%rsp), %eax\n"
    "        cmp     L_MCOUNT(%rsp), %eax\n"
    "        je      .Lmw_refill\n"
    ".Lmw_lookup:\n"
    "        mov     L_MNEXT(%rsp), %eax\n"
    "        cmp     L_MCOUNT(%rsp), %eax\n"
    "        jae     .Lmw_scalar\n"
    "        movzwl  L_AT(%rsp,%rax,2), %ecx\n"
    "        mov     %rbx, %rdx\n"
    "        sub     L_BUF(%rsp), %rdx\n"
    "        cmp     %edx, %ecx\n"
    "        jne     .Lmw_scalar\n"
    "        mov     %eax, %ecx\n"
    "        shr     $4, %ecx\n"
    "        shl     $7, %ecx\n"
    "        and     $15, %eax\n"
    "        lea     L_RES(%rsp,%rcx), %rsi\n"
    "        mov     (%rsi,%rax,4), %edx\n"
    "        mov     64(%rsi,%rax,4), %ecx\n"
    "        and     $-2, %edx\n"
    "        cmp     $0xfffffffe, %edx\n"
    "        jne     1f\n"
    "        mov     $0xfffffffc, %edx\n"
    "1:\n"
    "        mov     %edx, MW_DX_HASH(%r14)\n"
    "        mov     %ecx, MW_DX_MINOR(%r14)\n"
    "        incl    L_MNEXT(%rsp)\n"
    "        jmp     .Lmw_hashed\n"

    ".Lmw_hid:\n"
    "        movzbl  6(%rbx), %ecx\n"
    "        xor     %eax, %eax\n"
    "        xor     %edx, %edx\n"
    "        test    %ecx, %ecx\n"
    "        jz      1f\n"
    "        cmpl    $0, (%rbx)\n"
    "        je      1f\n"
    "        lea     11(%rcx), %ecx\n"
    "        and     $-4, %ecx\n"
    "        mov     (%rbx,%rcx), %eax\n"
    "        mov     4(%rbx,%rcx), %edx\n"
    "1:\n"
    "        mov     %eax, MW_DX_HASH(%r14)\n"
    "        mov     %edx, MW_DX_MINOR(%r14)\n"
    "        jmp     .Lmw_hashed\n"

    ".Lmw_scalar:\n"
    "        mov     %r13, %rdi\n"
    "        lea     8(%rbx), %rsi\n"
    "        movzbl  6(%rbx), %edx\n"
    "        mov     %r14, %rcx\n"
    "        call    ext4fs_dirhash\n"
    "        test    %eax, %eax\n"
    "        jns     .Lmw_hashed\n"
    "        mov     %eax, L_COUNT(%rsp)\n"
    "        jmp     .Lmw_done\n"

    "        # before the start of this readdir, or deleted: skip\n"
    ".Lmw_hashed:\n"
    "        mov     MW_DX_HASH(%r14), %eax\n"
    "        cmp     L_SHASH(%rsp), %eax\n"
    "        jb      .Lmw_next\n"
    "        ja      1f\n"
    "        mov     MW_DX_MINOR(%r14), %edx\n"
    "        cmp     L_SMINOR(%rsp), %edx\n"
    "        jb      .Lmw_next\n"
    "1:\n"
    "        cmpl    $0, (%rbx)\n"
    "        je      .Lmw_next\n"
#ifdef CONFIG_FS_ENCRYPTION
    "        testl   $MW_S_ENCRYPTED, MW_INODE_FLAGS(%r13)\n"
    "        jnz     .Lmw_encstore\n"
#endif
    "        lea     8(%rbx), %rax\n"
    "        mov     %rax, L_TMP(%rsp)\n"
    "        movzbl  6(%rbx), %eax\n"
    "        mov     %eax, L_TMP+8(%rsp)\n"
    "        mov     %r12, %rdi\n"
    "        mov     MW_DX_HASH(%r14), %esi\n"
    "        mov     MW_DX_MINOR(%r14), %edx\n"
    "        mov     %rbx, %rcx\n"
    "        lea     L_TMP(%rsp), %r8\n"
    "        call    ext4_htree_store_dirent\n"
    "        jmp     .Lmw_stored\n"
#ifdef CONFIG_FS_ENCRYPTION
    ".Lmw_encstore:\n"
    "        mov     L_FSTR+8(%rsp), %eax\n"
    "        mov     %eax, L_SAVELEN(%rsp)\n"
    "        lea     8(%rbx), %rax\n"
    "        mov     %rax, L_TMP(%rsp)\n"
    "        movzbl  6(%rbx), %eax\n"
    "        mov     %eax, L_TMP+8(%rsp)\n"
    "        mov     %r13, %rdi\n"
    "        mov     MW_DX_HASH(%r14), %esi\n"
    "        mov     MW_DX_MINOR(%r14), %edx\n"
    "        lea     L_TMP(%rsp), %rcx\n"
    "        lea     L_FSTR(%rsp), %r8\n"
    "        call    fscrypt_fname_disk_to_usr\n"
    "        test    %eax, %eax\n"
    "        jnz     .Lmw_storeerr\n"
    "        mov     %r12, %rdi\n"
    "        mov     MW_DX_HASH(%r14), %esi\n"
    "        mov     MW_DX_MINOR(%r14), %edx\n"
    "        mov     %rbx, %rcx\n"
    "        lea     L_FSTR(%rsp), %r8\n"
    "        call    ext4_htree_store_dirent\n"
    "        mov     L_SAVELEN(%rsp), %ecx\n"
    "        mov     %ecx, L_FSTR+8(%rsp)\n"
#endif
    ".Lmw_stored:\n"
    "        test    %eax, %eax\n"
    "        jnz     .Lmw_storeerr\n"
    "        incl    L_COUNT(%rsp)\n"
    ".Lmw_next:\n"
    "        movzwl  4(%rbx), %eax\n"
    "        lea     -1(%rax), %ecx\n"
    "        cmp     $0xfffe, %ecx\n"
    "        jae     7f\n"
    "        mov     %eax, %ecx\n"
    "        and     $0xfffc, %eax\n"
    "        and     $3, %ecx\n"
    "        shl     $16, %ecx\n"
    "        or      %ecx, %eax\n"
    "        jmp     8f\n"
    "7:\n"
    "        mov     L_BLKSZ(%rsp), %eax\n"
    "8:\n"
    "        add     %rax, %rbx\n"
    "        jmp     .Lmw_loop\n"
    ".Lmw_storeerr:\n"
    "        mov     %eax, L_COUNT(%rsp)\n"

    "        # errout: brelse(bh); fscrypt_fname_free_buffer(&fname_crypto_str); return count\n"
    ".Lmw_done:\n"
    "        mov     %r15, %rdi\n"
    "        call    __brelse\n"
#ifdef CONFIG_FS_ENCRYPTION
    "        testl   $MW_S_ENCRYPTED, MW_INODE_FLAGS(%r13)\n"
    "        jz      1f\n"
    "        lea     L_FSTR(%rsp), %rdi\n"
    "        call    fscrypt_fname_free_buffer\n"
    "1:\n"
#endif
    "        mov     L_COUNT(%rsp), %eax\n"
    "        jmp     .Lmw_out\n"
#ifdef CONFIG_FS_ENCRYPTION
    ".Lmw_brelse_exit:\n"
    "        mov     %eax, L_COUNT(%rsp)\n"
    "        mov     %r15, %rdi\n"
    "        call    __brelse\n"
    "        mov     L_COUNT(%rsp), %eax\n"
#endif
    ".Lmw_readerr:\n"
    ".Lmw_out:\n"
    "        add     $L_FRAME, %rsp\n"
    "        pop     %rbx\n"
    "        pop     %r12\n"
    "        pop     %r13\n"
    "        pop     %r14\n"
    "        pop     %r15\n"
    "        pop     %rbp\n"
    "        " ASM_RET

    "        # the batch: find the next live names from the entry in rbx, hash them together\n"
    ".Lmw_refill:\n"
    "        movl    $0, L_MCOUNT(%rsp)\n"
    "        movl    $0, L_MNEXT(%rsp)\n"
    "        xor     %r10d, %r10d\n"
    "        mov     %rbx, %r11\n"
    ".Lmw_fl:\n"
    "        cmp     %rbp, %r11\n"
    "        jae     .Lmw_fe\n"
    "        cmp     $64, %r10d\n"
    "        jae     .Lmw_fe\n"
    "        lea     12(%r11), %rax\n"
    "        cmp     L_END(%rsp), %rax\n"
    "        ja      .Lmw_fe\n"
    "        movzwl  4(%r11), %r8d\n"
    "        lea     -1(%r8), %ecx\n"
    "        cmp     $0xfffe, %ecx\n"
    "        jae     7f\n"
    "        mov     %r8d, %ecx\n"
    "        and     $0xfffc, %r8d\n"
    "        and     $3, %ecx\n"
    "        shl     $16, %ecx\n"
    "        or      %ecx, %r8d\n"
    "        jmp     8f\n"
    "7:\n"
    "        mov     L_BLKSZ(%rsp), %r8d\n"
    "8:\n"
    "        cmp     $12, %r8d\n"
    "        jb      .Lmw_fe\n"
    "        test    $3, %r8b\n"
    "        jnz     .Lmw_fe\n"
    "        lea     (%r11,%r8), %rax\n"
    "        cmp     L_END(%rsp), %rax\n"
    "        ja      .Lmw_fe\n"
    "        cmpl    $0, (%r11)\n"
    "        je      .Lmw_fa\n"
    "        movzbl  6(%r11), %ecx\n"
    "        test    %ecx, %ecx\n"
    "        jz      .Lmw_fa\n"
    "        lea     8(%rcx), %eax\n"
    "        cmp     %r8d, %eax\n"
    "        ja      .Lmw_fa\n"
    "        lea     31(%rcx), %eax\n"
    "        and     $-32, %eax\n"
    "        lea     8(%r11,%rax), %rax\n"
    "        cmp     L_END(%rsp), %rax\n"
    "        ja      .Lmw_fa\n"
    "        mov     %r11, %rax\n"
    "        sub     L_BUF(%rsp), %rax\n"
    "        mov     %ax, L_AT(%rsp,%r10,2)\n"
    "        add     $8, %eax\n"
    "        mov     %eax, L_NOFF(%rsp,%r10,4)\n"
    "        mov     %ecx, L_LEN(%rsp,%r10,4)\n"
    "        inc     %r10d\n"
    ".Lmw_fa:\n"
    "        add     %r8, %r11\n"
    "        jmp     .Lmw_fl\n"
    ".Lmw_fe:\n"
    "        cmp     $16, %r10d\n"
    "        jb      .Lmw_off\n"
    "        mov     %r10d, L_N(%rsp)\n"
    "        mov     L_NOFF-4(%rsp,%r10,4), %eax\n"
    "        mov     L_LEN-4(%rsp,%r10,4), %ecx\n"
    "        mov     %r10d, %edx\n"
    ".Lmw_pad:\n"
    "        test    $15, %edx\n"
    "        jz      .Lmw_padded\n"
    "        mov     %eax, L_NOFF(%rsp,%rdx,4)\n"
    "        mov     %ecx, L_LEN(%rsp,%rdx,4)\n"
    "        inc     %edx\n"
    "        jmp     .Lmw_pad\n"
    ".Lmw_padded:\n"
    "        shr     $4, %edx\n"
    "        mov     %edx, L_NCHUNK(%rsp)\n"
    "        cmpb    $0, moonwater_dirhash_simd(%rip)\n"
    "        je      .Lmw_off\n"
    "        testl   $(1<<MW_AVX2_BIT), boot_cpu_data+MW_CPU_CAP+4*MW_AVX2_WORD(%rip)\n"
    "        jz      .Lmw_off\n"
    "        call    irq_fpu_usable\n"
    "        test    %al, %al\n"
    "        jz      .Lmw_off\n"
    "        mov     $2, %edi\n"
    "        call    kernel_fpu_begin_mask\n"
    "        movl    $0, L_K(%rsp)\n"
    ".Lmw_chunk:\n"
    "        mov     L_K(%rsp), %eax\n"
    "        cmp     L_NCHUNK(%rsp), %eax\n"
    "        jae     .Lmw_chunks\n"
    "        mov     %eax, %ecx\n"
    "        shl     $6, %ecx\n"
    "        lea     L_NOFF(%rsp,%rcx), %rsi\n"
    "        lea     L_LEN(%rsp,%rcx), %rdx\n"
    "        shl     $1, %ecx\n"
    "        lea     L_RES(%rsp,%rcx), %r9\n"
    "        mov     L_BUF(%rsp), %rdi\n"
    "        lea     L_STATE(%rsp), %rcx\n"
    "        mov     L_FLAGS(%rsp), %r8d\n"
    "        call    hash_half_md4_wide\n"
    "        incl    L_K(%rsp)\n"
    "        jmp     .Lmw_chunk\n"
    ".Lmw_chunks:\n"
    "        call    kernel_fpu_end\n"
    "        mov     L_N(%rsp), %eax\n"
    "        mov     %eax, L_MCOUNT(%rsp)\n"
    "        jmp     .Lmw_lookup\n"
    ".Lmw_off:\n"
    "        movl    $0, L_ON(%rsp)\n"
    "        jmp     .Lmw_scalar\n"

    "        .pushsection .rodata.str1.1, \"aMS\", @progbits, 1\n"
    ".Lmw_fn:\n"
    "        .asciz  \"htree_dirblock_to_tree\"\n"
    "        .popsection\n"
    ASM_END(htree_dirblock_to_tree)
);
#endif // CONFIG_X86_64

#endif // KERNEL_KERNEL_C

